[package]
name = "memorypack-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
memorypack = { path = "../../memorypack" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
dhat = "0.3"

[[bench]]
name = "memorypack_bench"
harness = false
