[package]
name = "memorypack-benchmark"

version = "0.0.1"
edition.workspace = true

publish = false

[features]
dhat-heap = ["dhat"]

[dependencies]
memorypack = { workspace = true }

dhat = { version = "0.3", optional = true }

[dev-dependencies]
divan = { package = "codspeed-divan-compat", version = "*" }

[[bench]]
name = "memorypack_bench"
harness = false
