[package]
name = "memorypack-benchmark"

version = "0.0.1"
edition.workspace = true

publish = false

[features]
dhat-heap = ["dhat"]

[dependencies]
ahash = "0.8"
dhat = { version = "0.3", optional = true }
memorypack = { path = "../../memorypack", features = ["ahash"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "memorypack_bench"
harness = false
