[package]
name = "memorypack-benchmark"

version = "0.0.1"
edition.workspace = true

publish = false

[features]
dhat-heap = ["dhat"]

[dependencies]
dhat = { version = "0.3", optional = true }
memorypack = { path = "../../memorypack" }

[dev-dependencies]
divan = { package = "codspeed-divan-compat", version = "*" }

[[bench]]
name = "memorypack_bench"
harness = false
